services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "3000:3000"
    #networks:
    #  - app-network
    restart: unless-stopped
#networks:
#  app-network:
